SGC fix for relocatable and contiguous gmp storage

diff --git a/gcl/configure b/gcl/configure
--- a/gcl/configure
+++ b/gcl/configure
@@ -1685,20 +1685,20 @@ if test "$enable_pic" = "yes" ; then
 	TCFLAGS="$TCFLAGS -fPIC"
 fi
 
-FDEBUG=`echo $CFLAGS | tr ' ' '\012' |grep "^\-g$"`
+FDEBUG=`echo $CFLAGS | tr ' ' '\012' |grep "^\-g$"|tr '\012' ' '`
 #CFLAGS=`echo $CFLAGS | tr ' ' '\012' |grep -v "^\-g$"`
-FOMITF=`echo $CFLAGS | tr ' ' '\012' |grep "^\-fomit-frame-pointer$"`
-CFLAGS=`echo $CFLAGS | tr ' ' '\012' |grep -v "^\-fomit-frame-pointer$"`
-FOOPT3=`echo $CFLAGS | tr ' ' '\012' |grep "^\-O3$"`
-CFLAGS=`echo $CFLAGS | tr ' ' '\012' |grep -v "^\-O3$"`
-FOOPT2=`echo $CFLAGS | tr ' ' '\012' |grep "^\-O2$"`
-CFLAGS=`echo $CFLAGS | tr ' ' '\012' |grep -v "^\-O2$"`
-FOOPT1=`echo $CFLAGS | tr ' ' '\012' |grep "^\-O1$"`
-TMP=`echo $CFLAGS | tr ' ' '\012' |grep "^\-O$"`
+FOMITF=`echo $CFLAGS | tr ' ' '\012' |grep "^\-fomit-frame-pointer$"|tr '\012' ' '`
+CFLAGS=`echo $CFLAGS | tr ' ' '\012' |grep -v "^\-fomit-frame-pointer$"|tr '\012' ' '`
+FOOPT3=`echo $CFLAGS | tr ' ' '\012' |grep "^\-O3$"|tr '\012' ' '`
+CFLAGS=`echo $CFLAGS | tr ' ' '\012' |grep -v "^\-O3$"|tr '\012' ' '`
+FOOPT2=`echo $CFLAGS | tr ' ' '\012' |grep "^\-O2$"|tr '\012' ' '`
+CFLAGS=`echo $CFLAGS | tr ' ' '\012' |grep -v "^\-O2$"|tr '\012' ' '`
+FOOPT1=`echo $CFLAGS | tr ' ' '\012' |grep "^\-O1$"|tr '\012' ' '`
+TMP=`echo $CFLAGS | tr ' ' '\012' |grep "^\-O$"|tr '\012' ' '`
 FOOPT1="$FOOPT1$TMP"
-CFLAGS=`echo $CFLAGS | tr ' ' '\012' |grep -v "^\-O1$"|grep -v "^\-O$"`
-FOOPT0=`echo $CFLAGS | tr ' ' '\012' |grep "^\-O0$"`
-CFLAGS=`echo $CFLAGS | tr ' ' '\012' |grep -v "^\-O0$"`
+CFLAGS=`echo $CFLAGS | tr ' ' '\012' |grep -v "^\-O1$"|grep -v "^\-O$"|tr '\012' ' '`
+FOOPT0=`echo $CFLAGS | tr ' ' '\012' |grep "^\-O0$"|tr '\012' ' '`
+CFLAGS=`echo $CFLAGS | tr ' ' '\012' |grep -v "^\-O0$"|tr '\012' ' '`
 
 if test "$FOOPT0" != "" ; then
    TO3FLAGS=`echo $TO3FLAGS | sed 's,\-O[123 ],-O0 ,g' | sed 's,\-O$,-O0 ,g'`
@@ -2741,7 +2741,7 @@ if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
 			echo $ac_n "checking if need to define CONST for bfd""... $ac_c" 1>&6
 echo "configure:2743: checking if need to define CONST for bfd" >&5
 			if test "$cross_compiling" = yes; then
-  echo "$ac_t""cannot use bfd" 1>&6 exit 1;
+  { echo "configure: error: cannot use bfd" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
 #line 2748 "configure"
@@ -2758,7 +2758,7 @@ else
   cat conftest.$ac_ext >&5
   rm -fr conftest*
   if test "$cross_compiling" = yes; then
-  echo "$ac_t""cannot use bfd" 1>&6 exit 1;
+  { echo "configure: error: cannot use bfd" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
 #line 2765 "configure"
@@ -2779,7 +2779,7 @@ else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
   rm -fr conftest*
-  echo "$ac_t""cannot use bfd" 1>&6 exit 1;
+  { echo "configure: error: cannot use bfd" 1>&2; exit 1; }
 fi
 rm -fr conftest*
 fi
